package deka:hello@0.1.0;

interface api {
  record position {
    x: f64,
    y: f64,
  }

  record user {
    name: string,
    age: u32,
  }

  greet: func(name: string) -> string;
  get-position: func() -> position;
  make-user: func(name: string, age: u32) -> user;
}

world hello {
  export api;
}
