// Generated by deka build. Do not edit manually.
// Source: /Users/sami/Projects/deka/mvp2/tests/phpx/jsx/typed_interface_props.phpx
// Target semantics: JavaScript runtime semantics.
// Fallback scaffold used because subset emitter could not lower this file.
export const phpxBuildMode = "scaffold";
export const phpxTargetSemantics = "js";
export const phpxBuildReason = "class-like declarations are not supported in JS subset emitter";
export const phpxSource = "/*\nTEST: JSX typed interface props runtime call\nCovers: component invocation passes object-shaped props compatible with interface/destructured params.\n*/\n\nimport { renderToString } from 'component/dom'\n\ninterface HelloProps {\n  $name: string\n}\n\nfunction Hello({ $name }: HelloProps): string {\n  return $name\n}\n\necho renderToString(<h1>Hello <Hello name=\"world\" /></h1>) . \"\\n\"\n";
export const phpxFile = "/Users/sami/Projects/deka/mvp2/tests/phpx/jsx/typed_interface_props.phpx";

export async function runPhpx(runtime, props = {}) {
if (!runtime || typeof runtime.executePhpx !== 'function') {
throw new Error('runtime.executePhpx(source, file, props) is required');
}
return await runtime.executePhpx(phpxSource, phpxFile, props);
}
