// Generated by deka build. Do not edit manually.
// Source: /Users/sami/Projects/deka/mvp2/php_modules/array/array_walk.phpx
// Target semantics: JavaScript runtime semantics.
// Fallback scaffold used because subset emitter could not lower this file.
export const phpxBuildMode = "scaffold";
export const phpxTargetSemantics = "js";
export const phpxBuildReason = "mixed or complex array items are not supported in subset emitter";
export const phpxSource = "/// docid: php/array/array_walk()\n/// <Function name=\"array_walk\">\n///   <Description>\n///     Applies a callback to each element of an array.\n///   </Description>\n///   <Parameter name=\"$array\" type=\"array\" required=\"true\" typeLink=\"/docs/php/types/array\">\n///     Array to walk.\n///   </Parameter>\n///   <Parameter name=\"$callback\" type=\"callable\" required=\"true\" typeLink=\"/docs/php/types/callable\">\n///     Callback to apply.\n///   </Parameter>\n///   <Parameter name=\"$userdata\" type=\"mixed\" required=\"false\" typeLink=\"/docs/php/types/mixed\">\n///     Optional user data.\n///   </Parameter>\n///   <ReturnType type=\"bool\" typeLink=\"/docs/php/types/bool\" />\n/// </Function>\nexport function array_walk(&$array, $callback, $userdata = null) {\n    $argc = func_num_args();\n    if ($argc < 2 || $argc > 3) {\n        return null;\n    }\n\n    if (!is_array($array)) {\n        return null;\n    }\n\n    foreach ($array as $key => $_) {\n        if ($argc === 3) {\n            call_user_func_array($callback, [&$array[$key], $key, $userdata]);\n        } else {\n            call_user_func_array($callback, [&$array[$key], $key]);\n        }\n    }\n\n    return true;\n}\n";
export const phpxFile = "/Users/sami/Projects/deka/mvp2/php_modules/array/array_walk.phpx";

export async function runPhpx(runtime, props = {}) {
if (!runtime || typeof runtime.executePhpx !== 'function') {
throw new Error('runtime.executePhpx(source, file, props) is required');
}
return await runtime.executePhpx(phpxSource, phpxFile, props);
}
