// Generated by deka build. Do not edit manually.
// Source: /Users/sami/Projects/deka/mvp2/php_modules/array/array_walk_recursive.phpx
// Target semantics: JavaScript runtime semantics.
// Fallback scaffold used because subset emitter could not lower this file.
export const phpxBuildMode = "scaffold";
export const phpxTargetSemantics = "js";
export const phpxBuildReason = "mixed or complex array items are not supported in subset emitter";
export const phpxSource = "/// docid: php/array/array_walk_recursive()\n/// <Function name=\"array_walk_recursive\">\n///   <Description>\n///     Applies a callback to each element of an array recursively.\n///   </Description>\n///   <Parameter name=\"$array\" type=\"array\" required=\"true\" typeLink=\"/docs/php/types/array\">\n///     Array to walk.\n///   </Parameter>\n///   <Parameter name=\"$callback\" type=\"callable\" required=\"true\" typeLink=\"/docs/php/types/callable\">\n///     Callback to apply.\n///   </Parameter>\n///   <Parameter name=\"$userdata\" type=\"mixed\" required=\"false\" typeLink=\"/docs/php/types/mixed\">\n///     Optional user data.\n///   </Parameter>\n///   <ReturnType type=\"bool\" typeLink=\"/docs/php/types/bool\" />\n/// </Function>\nexport function array_walk_recursive(&$array, $callback, $userdata = null) {\n    $argc = func_num_args();\n    if ($argc < 2 || $argc > 3) {\n        return null;\n    }\n\n    if (!is_array($array)) {\n        return null;\n    }\n\n    $withUserData = $argc === 3;\n    __deka_walk_recursive($array, $callback, $userdata, $withUserData);\n    return true;\n}\n\nfunction __deka_walk_recursive(&$array, $callback, $userdata, $withUserData) {\n    foreach ($array as $key => $value) {\n        if (is_array($value)) {\n            __deka_walk_recursive($array[$key], $callback, $userdata, $withUserData);\n        } else {\n            if ($withUserData) {\n                call_user_func_array($callback, [&$array[$key], $key, $userdata]);\n            } else {\n                call_user_func_array($callback, [&$array[$key], $key]);\n            }\n        }\n    }\n}\n";
export const phpxFile = "/Users/sami/Projects/deka/mvp2/php_modules/array/array_walk_recursive.phpx";

export async function runPhpx(runtime, props = {}) {
if (!runtime || typeof runtime.executePhpx !== 'function') {
throw new Error('runtime.executePhpx(source, file, props) is required');
}
return await runtime.executePhpx(phpxSource, phpxFile, props);
}
