// Generated by build.rs (Static prelude). Do not edit.
if (!globalThis.Response) {
    globalThis.Response = class Response1 {
        body;
        status;
        headers;
        constructor(body, init){
            this.body = body || '';
            this.status = init?.status || 200;
            this.headers = init?.headers || {};
        }
    };
}
const MIME_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".htm": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".mjs": "application/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".map": "application/json; charset=utf-8",
    ".svg": "image/svg+xml; charset=utf-8",
    ".txt": "text/plain; charset=utf-8",
    ".xml": "application/xml; charset=utf-8",
    ".pdf": "application/pdf",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".ico": "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf": "font/ttf",
    ".eot": "application/vnd.ms-fontobject",
    ".otf": "font/otf"
};
function contentType(path) {
    const lastDot = path.lastIndexOf('.');
    const ext = lastDot === -1 ? '' : path.slice(lastDot).toLowerCase();
    return MIME_TYPES[ext] || "application/octet-stream";
}
function serveStatic(filePath, content) {
    return {
        fetch (request) {
            return new Response(content, {
                status: 200,
                headers: {
                    "Content-Type": contentType(filePath)
                }
            });
        }
    };
}
function serveStaticDirectory(directoryPath, options = {}) {
    const directoryListing = options.directory_listing !== false;
    return {
        async fetch (req) {
            const url = new URL(req.url || "http://localhost/");
            let pathname = url.pathname || "/";
            if (!pathname.startsWith("/")) pathname = `/${pathname}`;
            if (directoryListing && pathname.endsWith("/")) {
                const listing = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Index of ${pathname}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      max-width: 900px;
      margin: 40px auto;
      padding: 0 20px;
      line-height: 1.6;
    }
    h1 {
      border-bottom: 1px solid #e0e0e0;
      padding-bottom: 10px;
    }
  </style>
</head>
<body>
  <h1>Index of ${pathname}</h1>
  <p><em>Directory: ${directoryPath}</em></p>
</body>
</html>`;
                return new Response(listing, {
                    status: 200,
                    headers: {
                        "Content-Type": "text/html; charset=utf-8"
                    }
                });
            }
            return new Response("Not Found", {
                status: 404
            });
        }
    };
}
globalThis.__dekaStatic = {
    serveStatic,
    serveStaticDirectory
};
export { serveStatic as serveStatic };
export { serveStaticDirectory as serveStaticDirectory };
