-- AUTO-GENERATED MIGRATION - DO NOT EDIT MANUALLY
-- Generated by deka db generate (manually adjusted to match Linkhash schema defaults)

CREATE TABLE IF NOT EXISTS "runtime_probe_logs" (
  "driver" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "lh_users" (
  "id" BIGSERIAL PRIMARY KEY,
  "did" TEXT NOT NULL UNIQUE,
  "handle" TEXT NOT NULL UNIQUE,
  "display_name" TEXT,
  "avatar_url" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "lh_sessions" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" BIGINT NOT NULL REFERENCES "lh_users"("id") ON DELETE CASCADE,
  "session_token_hash" TEXT NOT NULL UNIQUE,
  "csrf_token_hash" TEXT,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "last_seen_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "expires_at" TIMESTAMPTZ NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "revoked_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "lh_api_tokens" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" BIGINT NOT NULL REFERENCES "lh_users"("id") ON DELETE CASCADE,
  "token_prefix" TEXT NOT NULL,
  "token_hash" TEXT NOT NULL UNIQUE,
  "scope_mask" INTEGER NOT NULL,
  "label" TEXT,
  "last_used_at" TIMESTAMPTZ,
  "expires_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "revoked_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "lh_orgs" (
  "id" BIGSERIAL PRIMARY KEY,
  "handle" TEXT NOT NULL UNIQUE,
  "visibility" TEXT NOT NULL DEFAULT 'public',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "lh_org_members" (
  "id" BIGSERIAL PRIMARY KEY,
  "org_id" BIGINT NOT NULL REFERENCES "lh_orgs"("id") ON DELETE CASCADE,
  "user_id" BIGINT NOT NULL REFERENCES "lh_users"("id") ON DELETE CASCADE,
  "role" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "revoked_at" TIMESTAMPTZ,
  UNIQUE ("org_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "lh_rate_limit_hits" (
  "id" BIGSERIAL PRIMARY KEY,
  "bucket" TEXT NOT NULL,
  "subject_key" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "lh_event_logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "level" TEXT NOT NULL DEFAULT 'info',
  "event" TEXT NOT NULL,
  "request_id" TEXT,
  "method" TEXT,
  "path" TEXT,
  "meta_json" TEXT
);

CREATE TABLE IF NOT EXISTS "lh_audit_logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "action" TEXT NOT NULL,
  "result" TEXT NOT NULL DEFAULT 'ok',
  "actor_user_id" BIGINT,
  "actor_handle" TEXT,
  "auth_kind" TEXT,
  "scope_mask" INTEGER NOT NULL DEFAULT 0,
  "subject_kind" TEXT,
  "subject_ref" TEXT,
  "request_id" TEXT,
  "method" TEXT,
  "path" TEXT,
  "ip_address" TEXT,
  "detail_json" TEXT
);

CREATE TABLE IF NOT EXISTS "packages" (
  "id" BIGSERIAL PRIMARY KEY,
  "org_id" BIGINT NOT NULL REFERENCES "lh_orgs"("id") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT '',
  "latest_version" TEXT NOT NULL DEFAULT '0.1.0',
  "download_count" BIGINT NOT NULL DEFAULT 0,
  "visibility" TEXT NOT NULL DEFAULT 'public',
  "private_read_mask" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "package_versions" (
  "id" BIGSERIAL PRIMARY KEY,
  "package_id" BIGINT NOT NULL REFERENCES "packages"("id") ON DELETE CASCADE,
  "version" TEXT NOT NULL,
  "main_file" TEXT DEFAULT 'index.phpx',
  "files" JSONB NOT NULL DEFAULT '[]'::JSONB,
  "dependencies" JSONB NOT NULL DEFAULT '{}'::JSONB,
  "readme" TEXT NOT NULL DEFAULT '',
  "published_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "r2_key" TEXT,
  "sha256" TEXT,
  "canonical_id" TEXT,
  "lock_hash" TEXT,
  "integrity_algo" TEXT,
  "module_graph_hash" TEXT,
  "fs_graph_hash" TEXT,
  "artifact_backend" TEXT NOT NULL DEFAULT 'local',
  "artifact_key" TEXT,
  "artifact_mime" TEXT NOT NULL DEFAULT 'application/octet-stream',
  "artifact_size_bytes" BIGINT NOT NULL DEFAULT 0,
  "artifact_inline_b64" TEXT,
  "capability_metadata" JSONB
);

CREATE TABLE IF NOT EXISTS "downloads" (
  "id" BIGSERIAL PRIMARY KEY,
  "package_id" BIGINT NOT NULL REFERENCES "packages"("id") ON DELETE CASCADE,
  "version_id" BIGINT NOT NULL REFERENCES "package_versions"("id") ON DELETE CASCADE,
  "downloaded_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "ip_address" TEXT,
  "user_agent" TEXT
);
