-- AUTO-GENERATED MIGRATION - DO NOT EDIT MANUALLY
-- Generated by deka db generate

CREATE TABLE IF NOT EXISTS "runtime_probe_logs" (
  "driver" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "lh_users" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "did" TEXT NOT NULL UNIQUE,
  "handle" TEXT NOT NULL UNIQUE,
  "display_name" TEXT NOT NULL,
  "avatar_url" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "lh_sessions" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "session_token_hash" TEXT NOT NULL UNIQUE,
  "csrf_token_hash" TEXT NOT NULL,
  "ip_address" TEXT NOT NULL,
  "user_agent" TEXT NOT NULL,
  "last_seen_at" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "revoked_at" TEXT
);


CREATE TABLE IF NOT EXISTS "lh_api_tokens" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "token_prefix" TEXT NOT NULL,
  "token_hash" TEXT NOT NULL UNIQUE,
  "scope_mask" BIGINT NOT NULL,
  "label" TEXT NOT NULL,
  "last_used_at" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "revoked_at" TEXT
);


CREATE TABLE IF NOT EXISTS "lh_orgs" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "handle" TEXT NOT NULL UNIQUE,
  "visibility" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "lh_org_members" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "org_id" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  "role" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "revoked_at" TEXT
);


CREATE TABLE IF NOT EXISTS "lh_rate_limit_hits" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "bucket" TEXT NOT NULL,
  "subject_key" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "lh_event_logs" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "created_at" TEXT NOT NULL,
  "level" TEXT NOT NULL,
  "event" TEXT NOT NULL,
  "request_id" TEXT NOT NULL,
  "method" TEXT NOT NULL,
  "path" TEXT NOT NULL,
  "meta_json" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "lh_audit_logs" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "created_at" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "result" TEXT NOT NULL,
  "actor_user_id" BIGINT NOT NULL,
  "actor_handle" TEXT NOT NULL,
  "auth_kind" TEXT NOT NULL,
  "scope_mask" BIGINT NOT NULL,
  "subject_kind" TEXT NOT NULL,
  "subject_ref" TEXT NOT NULL,
  "request_id" TEXT NOT NULL,
  "method" TEXT NOT NULL,
  "path" TEXT NOT NULL,
  "ip_address" TEXT NOT NULL,
  "detail_json" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "packages" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "org_id" BIGINT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "latest_version" TEXT NOT NULL,
  "download_count" BIGINT NOT NULL,
  "visibility" TEXT NOT NULL,
  "private_read_mask" BIGINT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "package_versions" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "package_id" BIGINT NOT NULL,
  "version" TEXT NOT NULL,
  "main_file" TEXT NOT NULL,
  "files" JSONB NOT NULL,
  "dependencies" JSONB NOT NULL,
  "readme" TEXT NOT NULL,
  "published_at" TEXT NOT NULL,
  "r2_key" TEXT NOT NULL,
  "sha256" TEXT NOT NULL,
  "canonical_id" TEXT NOT NULL,
  "lock_hash" TEXT NOT NULL,
  "integrity_algo" TEXT NOT NULL,
  "module_graph_hash" TEXT NOT NULL,
  "fs_graph_hash" TEXT NOT NULL,
  "artifact_backend" TEXT NOT NULL,
  "artifact_key" TEXT NOT NULL,
  "artifact_mime" TEXT NOT NULL,
  "artifact_size_bytes" BIGINT NOT NULL,
  "artifact_inline_b64" TEXT NOT NULL,
  "capability_metadata" JSONB NOT NULL
);


CREATE TABLE IF NOT EXISTS "downloads" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "package_id" BIGINT NOT NULL,
  "version_id" BIGINT NOT NULL,
  "downloaded_at" TEXT NOT NULL,
  "ip_address" TEXT NOT NULL,
  "user_agent" TEXT NOT NULL
);


