package user:enum-flags@0.1.0;

interface api {
  enum mode { off, turbo, read-only }
  flags perms { read, write, exec }

  get-mode: func() -> mode;
  toggle-mode: func(mode: mode) -> mode;
  get-perms: func() -> perms;
  echo-perms: func(perms: perms) -> perms;
}

world enum-flags {
  export api;
}
